_welcome:
    pattern:  /
    defaults: { _controller: SymbloggerSymblogBundle:Page:index }
    requirements:
        _method:  GET


_about:
    pattern:  /about
    defaults: { _controller: SymbloggerSymblogBundle:Page:about }
    requirements:
        _method:  GET

_contact:
    pattern:  /contact
    defaults: { _controller: SymbloggerSymblogBundle:Page:contact }
    requirements:
        _method:  GET|POST

_blog_show:
    pattern:  /{id}
    defaults: { _controller: SymbloggerSymblogBundle:Blog:show }
    requirements:
        _method:  GET
        id: \d+

_comment_create:
    pattern:  /comment/{blog_id}
    defaults: { _controller: SymbloggerSymblogBundle:Comment:create }
    requirements:
        _method:  POST
        blog_id: \d+