parameters:
#    symblogger_symblog.example.class: Symblogger\SymblogBundle\Example

services:
#    symblogger_symblog.example:
#        class: %symblogger_symblog.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
